llm:
  model: claude-haiku-4-5-20251001

cachier:
  cache_dir: llm_cache

evaluate:
  expt_name: td_workflow
  result_dir: results
  entry_point: answer_question_workflow
  record_details: true

dataset:
  split: true_detective
  shuffle_seed: 42
  n: null

ptools:
  raw_answer:
    method: simulate
  extract_index:
    method: simulate
  extract_clues_and_suspects:
    method: simulate
  verify_and_cross_reference:
    method: simulate
  deduce_guilty:
    method: simulate
  answer_question:
    method: direct
  answer_question_workflow:
    method: direct
